/**
 * adminProvider.js
 * ────────────────
 * Search items for the Admin Workspace.
 * All items are SUPER_ADMIN only.
 * Covers: pages, sections, actions, settings, docs.
 */
import { ENTITY_TYPE, PROVIDER_TYPE } from '../core/searchTypes.js';

const ITEMS = [
  // ── Pages ──────────────────────────────────────────────────────────────────
  {
    id:          'admin-dashboard',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Admin',
    category:    'Pages',
    page:        'Admin Dashboard',
    section:     null,
    description: 'Administration workspace overview — platform health, user stats, module status.',
    icon:        'Shield',
    badge:       null,
    navPath:     'Admin › Admin Dashboard',
    nav:         { page: 'admin', sub: 'admin-dashboard', tab: null, section: null, anchor: null, action: null },
    keywords:    ['admin', 'administration', 'dashboard', 'overview', 'superadmin', 'super admin', 'system'],
    synonyms:    ['admin panel', 'control panel', 'admin home'],
    acronyms:    ['adm'],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },
  {
    id:          'admin-users',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Admin',
    category:    'Pages',
    page:        'Manage Users',
    section:     null,
    description: 'Create, edit, activate and deactivate platform users.',
    icon:        'Users',
    badge:       null,
    navPath:     'Admin › User Management › Manage Users',
    nav:         { page: 'admin', sub: 'user-management', tab: null, section: null, anchor: null, action: null },
    keywords:    ['users', 'user', 'manage', 'user management', 'accounts', 'create user', 'edit user', 'deactivate'],
    synonyms:    ['user list', 'user accounts', 'team members'],
    acronyms:    ['um'],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },
  {
    id:          'admin-roles',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Admin',
    category:    'Pages',
    page:        'Role Management',
    section:     null,
    description: 'Define and manage user roles — permissions and access levels.',
    icon:        'UserCog',
    badge:       null,
    navPath:     'Admin › User Management › Role Management',
    nav:         { page: 'admin', sub: 'role-management', tab: null, section: null, anchor: null, action: null },
    keywords:    ['roles', 'role', 'permissions', 'access', 'role management', 'rbac', 'user roles'],
    synonyms:    ['user roles', 'permissions management', 'rbac'],
    acronyms:    ['rm'],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },
  {
    id:          'admin-access',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Admin',
    category:    'Pages',
    page:        'Access Management',
    section:     null,
    description: 'Configure IP allowlists and session policies for platform access control.',
    icon:        'KeyRound',
    badge:       'SOON',
    navPath:     'Admin › User Management › Access Management',
    nav:         { page: 'admin', sub: 'access-management', tab: null, section: null, anchor: null, action: null },
    keywords:    ['access', 'ip', 'allowlist', 'session', 'security', 'control', 'policy'],
    synonyms:    ['access control', 'ip whitelist', 'security policy'],
    acronyms:    ['acm'],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },
  {
    id:          'admin-env-config',
    entityType:  ENTITY_TYPE.SETTING,
    module:      'Admin',
    category:    'Settings',
    page:        'Environments Config',
    section:     null,
    description: 'Configure automation environments — URLs, variables, credentials per environment.',
    icon:        'Globe2',
    badge:       null,
    navPath:     'Admin › Automation › Environments',
    nav:         { page: 'admin', sub: 'environments-config', tab: null, section: null, anchor: null, action: null },
    keywords:    ['environments', 'environment', 'env', 'config', 'automation config', 'variables', 'urls', 'settings'],
    synonyms:    ['env settings', 'environment config', 'test environments'],
    acronyms:    ['env'],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },
  {
    id:          'admin-modules',
    entityType:  ENTITY_TYPE.SETTING,
    module:      'Admin',
    category:    'Settings',
    page:        'Module Management',
    section:     null,
    description: 'Manage automation test modules — create, edit, assign teams.',
    icon:        'Package',
    badge:       null,
    navPath:     'Admin › Automation › Module Management',
    nav:         { page: 'admin', sub: 'module-management', tab: null, section: null, anchor: null, action: null },
    keywords:    ['modules', 'module', 'module management', 'test modules', 'teams', 'assign'],
    synonyms:    ['test modules', 'module admin', 'manage modules'],
    acronyms:    ['mm'],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },
  {
    id:          'admin-portal-config',
    entityType:  ENTITY_TYPE.SETTING,
    module:      'Admin',
    category:    'Settings',
    page:        'System Config',
    section:     null,
    description: 'Platform-wide system configuration — notification settings, integrations, global options.',
    icon:        'Sliders',
    badge:       null,
    navPath:     'Admin › Automation › System Config',
    nav:         { page: 'admin', sub: 'portal-config', tab: null, section: null, anchor: null, action: null },
    keywords:    ['config', 'configuration', 'system', 'settings', 'global', 'portal config', 'options', 'preferences'],
    synonyms:    ['system settings', 'portal settings', 'platform config', 'global settings'],
    acronyms:    ['sc'],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },
  {
    id:          'admin-docs',
    entityType:  ENTITY_TYPE.DOCS,
    module:      'Admin',
    category:    'Documentation',
    page:        'Internal Documentation',
    section:     null,
    description: 'Internal platform documentation — guides, API specs, architecture notes.',
    icon:        'BookOpen',
    badge:       null,
    navPath:     'Admin › Documentation',
    nav:         { page: 'admin', sub: 'documentation', tab: null, section: null, anchor: null, action: null },
    keywords:    ['docs', 'documentation', 'guide', 'manual', 'help', 'reference', 'internal docs'],
    synonyms:    ['help docs', 'internal guide', 'platform docs'],
    acronyms:    ['doc'],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },
  {
    id:          'admin-api-collection',
    entityType:  ENTITY_TYPE.DOCS,
    module:      'Admin',
    category:    'Documentation',
    page:        'API Reference',
    section:     null,
    description: 'Full API reference collection for the Testrix platform — all REST endpoints.',
    icon:        'TerminalSquare',
    badge:       null,
    navPath:     'Admin › Documentation › API Reference',
    nav:         { page: 'admin', sub: 'api-collection', tab: null, section: null, anchor: null, action: null },
    keywords:    ['api reference', 'api docs', 'rest api', 'endpoints', 'swagger', 'openapi', 'collection'],
    synonyms:    ['api documentation', 'rest docs', 'api spec'],
    acronyms:    ['api'],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },

  // ── Actions ────────────────────────────────────────────────────────────────
  {
    id:          'admin-action-create-user',
    entityType:  ENTITY_TYPE.ACTION,
    module:      'Admin',
    category:    'Actions',
    page:        'Create New User',
    section:     null,
    description: 'Open User Management to add a new platform user.',
    icon:        'Users',
    badge:       null,
    navPath:     'Admin › User Management',
    nav:         { page: 'admin', sub: 'user-management', tab: null, section: null, anchor: null, action: 'admin-create-user' },
    keywords:    ['create user', 'new user', 'add user', 'invite', 'register user'],
    synonyms:    ['add user', 'invite user', 'new account'],
    acronyms:    [],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },
  {
    id:          'admin-action-manage-roles',
    entityType:  ENTITY_TYPE.ACTION,
    module:      'Admin',
    category:    'Actions',
    page:        'Manage User Roles',
    section:     null,
    description: 'Go to Role Management to assign or modify user roles.',
    icon:        'UserCog',
    badge:       null,
    navPath:     'Admin › Role Management',
    nav:         { page: 'admin', sub: 'role-management', tab: null, section: null, anchor: null, action: null },
    keywords:    ['manage roles', 'assign role', 'change role', 'permissions', 'role admin'],
    synonyms:    ['role assignment', 'change permissions'],
    acronyms:    [],
    disabled:    false,
    permission:  'SUPER_ADMIN',
    metadata:    {},
  },
];

export const adminProvider = {
  id:       'admin',
  type:     PROVIDER_TYPE.STATIC,
  priority: 20,
  getItems: () => ITEMS,
};
