/**
 * apiTestingProvider.js
 * ─────────────────────
 * Search items for the API Testing module.
 * Covers: pages, sections, actions, and reports.
 */
import { ENTITY_TYPE, PROVIDER_TYPE } from '../core/searchTypes.js';

const ITEMS = [
  // ── Pages ──────────────────────────────────────────────────────────────────
  {
    id:          'api-dashboard',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'API Testing',
    category:    'Pages',
    page:        'API Testing Dashboard',
    section:     null,
    description: 'API Testing overview — execution counts, success rates, and active schedules.',
    icon:        'LayoutDashboard',
    badge:       null,
    navPath:     'API Testing › Dashboard',
    nav:         { page: 'apitest', sub: 'dashboard', tab: null, section: null, anchor: null, action: null },
    keywords:    ['api', 'dashboard', 'overview', 'api testing', 'summary', 'kpi', 'success rate'],
    synonyms:    ['api home', 'api overview', 'api summary'],
    acronyms:    ['atd'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'api-tester',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'API Testing',
    category:    'Pages',
    page:        'API Tester',
    section:     null,
    description: 'Interactive API request builder — send requests, inspect responses.',
    icon:        'Send',
    badge:       null,
    navPath:     'API Testing › API Tester',
    nav:         { page: 'apitest', sub: 'tester', tab: null, section: null, anchor: null, action: null },
    keywords:    ['tester', 'api tester', 'request', 'send', 'postman', 'rest', 'http', 'builder', 'test api'],
    synonyms:    ['api client', 'request builder', 'http client', 'rest client'],
    acronyms:    ['at'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'api-base',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'API Testing',
    category:    'Pages',
    page:        'Base APIs',
    section:     null,
    description: 'Manage base API definitions — foundation endpoints shared across suites.',
    icon:        'Database',
    badge:       null,
    navPath:     'API Testing › Base APIs',
    nav:         { page: 'apitest', sub: 'base-apis', tab: null, section: null, anchor: null, action: null },
    keywords:    ['base', 'base api', 'apis', 'foundation', 'endpoints', 'definitions', 'core'],
    synonyms:    ['base endpoints', 'foundation apis', 'core apis'],
    acronyms:    ['ba'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'api-regular',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'API Testing',
    category:    'Pages',
    page:        'Regular APIs',
    section:     null,
    description: 'Manage standard API test cases — create, edit, organise and run.',
    icon:        'Workflow',
    badge:       null,
    navPath:     'API Testing › Regular APIs',
    nav:         { page: 'apitest', sub: 'regular-apis', tab: null, section: null, anchor: null, action: null },
    keywords:    ['regular', 'regular api', 'apis', 'tests', 'test cases', 'workflow'],
    synonyms:    ['api tests', 'test apis', 'api cases'],
    acronyms:    ['ra'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'api-scheduler',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'API Testing',
    category:    'Pages',
    page:        'API Scheduler',
    section:     null,
    description: 'Schedule API tests to run automatically — cron, interval or one-time.',
    icon:        'CalendarClock',
    badge:       null,
    navPath:     'API Testing › Scheduler',
    nav:         { page: 'apitest', sub: 'scheduler', tab: null, section: null, anchor: null, action: null },
    keywords:    ['scheduler', 'schedule', 'cron', 'automated', 'timer', 'recurring', 'interval', 'api schedule'],
    synonyms:    ['api scheduler', 'schedule tests', 'cron job', 'test schedule'],
    acronyms:    ['sched', 'as'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'api-history',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'API Testing',
    category:    'Pages',
    page:        'API History',
    section:     null,
    description: 'Full history of every API test execution — filter by status, date, module.',
    icon:        'History',
    badge:       null,
    navPath:     'API Testing › History',
    nav:         { page: 'apitest', sub: 'history', tab: null, section: null, anchor: null, action: null },
    keywords:    ['history', 'past', 'executions', 'runs', 'logs', 'past runs', 'api history'],
    synonyms:    ['execution history', 'past executions', 'run history', 'api logs'],
    acronyms:    ['ah'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'api-modules',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'API Testing',
    category:    'Pages',
    page:        'API Modules',
    section:     null,
    description: 'Organise API tests into logical modules — group, manage and execute per module.',
    icon:        'FolderTree',
    badge:       null,
    navPath:     'API Testing › Modules',
    nav:         { page: 'apitest', sub: 'modules', tab: null, section: null, anchor: null, action: null },
    keywords:    ['modules', 'module', 'folder', 'group', 'collection', 'organisation', 'api modules'],
    synonyms:    ['api collections', 'test groups', 'api folders'],
    acronyms:    ['am'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },

  // ── Actions ────────────────────────────────────────────────────────────────
  {
    id:          'api-action-new-api',
    entityType:  ENTITY_TYPE.ACTION,
    module:      'API Testing',
    category:    'Actions',
    page:        'Create New API',
    section:     null,
    description: 'Navigate to Regular APIs to add a new API test case.',
    icon:        'Send',
    badge:       null,
    navPath:     'API Testing › Regular APIs',
    nav:         { page: 'apitest', sub: 'regular-apis', tab: null, section: null, anchor: null, action: 'api-create' },
    keywords:    ['create', 'new api', 'add api', 'new test', 'create api', 'add'],
    synonyms:    ['add api', 'new endpoint', 'create endpoint'],
    acronyms:    [],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'api-action-schedule',
    entityType:  ENTITY_TYPE.ACTION,
    module:      'API Testing',
    category:    'Actions',
    page:        'Create API Schedule',
    section:     null,
    description: 'Open the Scheduler page to set up a new automated API run.',
    icon:        'CalendarClock',
    badge:       null,
    navPath:     'API Testing › Scheduler',
    nav:         { page: 'apitest', sub: 'scheduler', tab: null, section: null, anchor: null, action: 'api-schedule-create' },
    keywords:    ['create schedule', 'new schedule', 'schedule api', 'add schedule', 'automate'],
    synonyms:    ['add schedule', 'new cron', 'schedule run'],
    acronyms:    [],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },

  // ── Reports ────────────────────────────────────────────────────────────────
  {
    id:          'api-report-history',
    entityType:  ENTITY_TYPE.REPORT,
    module:      'API Testing',
    category:    'Reports',
    page:        'API Execution Report',
    section:     null,
    description: 'Detailed report of API test executions — status breakdown, response times.',
    icon:        'History',
    badge:       null,
    navPath:     'API Testing › History',
    nav:         { page: 'apitest', sub: 'history', tab: null, section: null, anchor: null, action: null },
    keywords:    ['api report', 'report', 'execution report', 'results', 'history', 'api results'],
    synonyms:    ['api execution report', 'test results'],
    acronyms:    [],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
];

export const apiTestingProvider = {
  id:       'api-testing',
  type:     PROVIDER_TYPE.STATIC,
  priority: 15,
  getItems: () => ITEMS,
};
