/**
 * automationProvider.js
 * ─────────────────────
 * Search items for the Automation module.
 * Covers: pages, sections, tabs, reports, and actions.
 */
import { ENTITY_TYPE, PROVIDER_TYPE } from '../core/searchTypes.js';

const ITEMS = [
  // ── Pages ──────────────────────────────────────────────────────────────────
  {
    id:          'auto-dashboard',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Automation',
    category:    'Pages',
    page:        'Automation Overview',
    section:     null,
    description: 'Automation suite overview with KPIs, trends, module health, and recent activity.',
    icon:        'Gauge',
    badge:       null,
    navPath:     'Automation › Overview',
    nav:         { page: 'automation', sub: 'dashboard', tab: null, section: null, anchor: null, action: null },
    keywords:    ['automation', 'dashboard', 'overview', 'kpi', 'summary', 'analytics'],
    synonyms:    ['automation home', 'automation overview', 'test summary'],
    acronyms:    ['ad'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'auto-execution',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Automation',
    category:    'Pages',
    page:        'Execution Center',
    section:     null,
    description: 'Run, manage and monitor test execution suites in real time.',
    icon:        'Play',
    badge:       null,
    navPath:     'Automation › Execution Center',
    nav:         { page: 'automation', sub: 'execution', tab: null, section: null, anchor: null, action: null },
    keywords:    ['execution', 'run', 'execute', 'test', 'suite', 'center', 'running', 'queued'],
    synonyms:    ['run tests', 'test runner', 'executions', 'execute tests'],
    acronyms:    ['ec'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'auto-reports',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Automation',
    category:    'Pages',
    page:        'Reports Center',
    section:     null,
    description: 'View, filter and download automation test execution reports.',
    icon:        'FileText',
    badge:       null,
    navPath:     'Automation › Reports Center',
    nav:         { page: 'automation', sub: 'reports', tab: null, section: null, anchor: null, action: null },
    keywords:    ['reports', 'report', 'results', 'download', 'export', 'test results', 'execution report'],
    synonyms:    ['automation reports', 'test reports', 'report center'],
    acronyms:    ['rc', 'ar'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'auto-logs',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Automation',
    category:    'Pages',
    page:        'Test Logs',
    section:     null,
    description: 'Detailed logs for every automated test run — search, filter and export.',
    icon:        'TerminalSquare',
    badge:       null,
    navPath:     'Automation › Test Logs',
    nav:         { page: 'automation', sub: 'logs', tab: null, section: null, anchor: null, action: null },
    keywords:    ['logs', 'log', 'test logs', 'output', 'terminal', 'debug', 'trace'],
    synonyms:    ['test output', 'console', 'automation logs'],
    acronyms:    ['tl'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'auto-screenshots',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Automation',
    category:    'Pages',
    page:        'Screenshots',
    section:     null,
    description: 'Visual evidence captured during test execution — browse and download screenshots.',
    icon:        'Camera',
    badge:       null,
    navPath:     'Automation › Screenshots',
    nav:         { page: 'automation', sub: 'screenshots', tab: null, section: null, anchor: null, action: null },
    keywords:    ['screenshots', 'screenshot', 'image', 'visual', 'evidence', 'capture', 'photo'],
    synonyms:    ['test screenshots', 'visual evidence', 'captured images'],
    acronyms:    ['ss'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'auto-compare',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Automation',
    category:    'Pages',
    page:        'Historical Compare',
    section:     null,
    description: 'Compare test execution results across time periods and identify regressions.',
    icon:        'GitCompare',
    badge:       null,
    navPath:     'Automation › Historical Compare',
    nav:         { page: 'automation', sub: 'compare', tab: null, section: null, anchor: null, action: null },
    keywords:    ['compare', 'historical', 'comparison', 'regression', 'diff', 'trend', 'history'],
    synonyms:    ['test comparison', 'regression analysis', 'historical analysis'],
    acronyms:    ['hc'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'auto-environments',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Automation',
    category:    'Pages',
    page:        'Environments',
    section:     null,
    description: 'Manage test environments — URLs, credentials, variables for automation runs.',
    icon:        'Globe2',
    badge:       null,
    navPath:     'Automation › Environments',
    nav:         { page: 'automation', sub: 'environments', tab: null, section: null, anchor: null, action: null },
    keywords:    ['environments', 'environment', 'env', 'config', 'variables', 'credentials', 'urls', 'settings'],
    synonyms:    ['test environments', 'env config', 'environment settings'],
    acronyms:    ['env'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },

  // ── Sections ───────────────────────────────────────────────────────────────
  {
    id:          'auto-execution-running',
    entityType:  ENTITY_TYPE.SECTION,
    module:      'Automation',
    category:    'Sections',
    page:        'Running Executions',
    section:     'Execution Center',
    description: 'View currently running test executions in real time.',
    icon:        'Play',
    badge:       null,
    navPath:     'Automation › Execution Center › Running',
    nav:         { page: 'automation', sub: 'execution', tab: null, section: 'running', anchor: null, action: null },
    keywords:    ['running', 'active', 'live', 'in progress', 'current execution'],
    synonyms:    ['active executions', 'live tests'],
    acronyms:    [],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },

  // ── Actions ────────────────────────────────────────────────────────────────
  {
    id:          'auto-action-run',
    entityType:  ENTITY_TYPE.ACTION,
    module:      'Automation',
    category:    'Actions',
    page:        'Run Automation Suite',
    section:     null,
    description: 'Navigate to Execution Center to start a new test execution.',
    icon:        'Play',
    badge:       null,
    navPath:     'Automation › Execution Center',
    nav:         { page: 'automation', sub: 'execution', tab: null, section: null, anchor: null, action: 'auto-run' },
    keywords:    ['run', 'start', 'execute', 'launch', 'automation', 'suite', 'trigger'],
    synonyms:    ['run tests', 'start tests', 'launch automation'],
    acronyms:    [],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'auto-action-download-report',
    entityType:  ENTITY_TYPE.ACTION,
    module:      'Automation',
    category:    'Actions',
    page:        'Download Automation Report',
    section:     null,
    description: 'Go to Reports Center to download an automation report.',
    icon:        'FileText',
    badge:       null,
    navPath:     'Automation › Reports Center',
    nav:         { page: 'automation', sub: 'reports', tab: null, section: null, anchor: null, action: null },
    keywords:    ['download', 'export', 'report', 'pdf', 'automation report'],
    synonyms:    ['get report', 'export report'],
    acronyms:    [],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },

  // ── Reports ────────────────────────────────────────────────────────────────
  {
    id:          'auto-report-execution',
    entityType:  ENTITY_TYPE.REPORT,
    module:      'Automation',
    category:    'Reports',
    page:        'Execution Report',
    section:     null,
    description: 'Full execution report with passed, failed, skipped counts and durations.',
    icon:        'FileText',
    badge:       null,
    navPath:     'Automation › Reports Center',
    nav:         { page: 'automation', sub: 'reports', tab: null, section: null, anchor: null, action: null },
    keywords:    ['execution report', 'report', 'results', 'passed', 'failed', 'skipped'],
    synonyms:    ['automation report', 'test report'],
    acronyms:    [],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
];

export const automationProvider = {
  id:       'automation',
  type:     PROVIDER_TYPE.STATIC,
  priority: 10,
  getItems: () => ITEMS,
};
