/**
 * performanceProvider.js
 * ──────────────────────
 * Search items for the Performance Testing module.
 */
import { ENTITY_TYPE, PROVIDER_TYPE } from '../core/searchTypes.js';

const ITEMS = [
  {
    id:          'perf-dashboard',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Performance',
    category:    'Pages',
    page:        'Performance Overview',
    section:     null,
    description: 'Performance Testing overview — run counts, pass rate, and active schedules.',
    icon:        'LayoutDashboard',
    badge:       null,
    navPath:     'Performance › Overview',
    nav:         { page: 'perf', sub: 'dashboard', tab: null, section: null, anchor: null, action: null },
    keywords:    ['performance', 'dashboard', 'overview', 'load test', 'k6', 'summary'],
    synonyms:    ['performance home', 'performance overview'],
    acronyms:    ['pt'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'perf-virtual-users',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Performance',
    category:    'Pages',
    page:        'Virtual Users',
    section:     null,
    description: 'Reusable simulated user profiles — auth, headers, params — assigned to Load Tests.',
    icon:        'Users',
    badge:       null,
    navPath:     'Performance › Virtual Users',
    nav:         { page: 'perf', sub: 'virtual-users', tab: null, section: null, anchor: null, action: null },
    keywords:    ['virtual user', 'vu', 'profile', 'simulated user', 'auth profile'],
    synonyms:    ['user profiles', 'vu workspace'],
    acronyms:    ['vu'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'perf-performance-tests',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Performance',
    category:    'Pages',
    page:        'Performance Tests',
    section:     null,
    description: 'Single-flow latency tests — P50–P99 thresholds and response assertions.',
    icon:        'Gauge',
    badge:       null,
    navPath:     'Performance › Performance Tests',
    nav:         { page: 'perf', sub: 'performance-tests', tab: null, section: null, anchor: null, action: null },
    keywords:    ['performance test', 'latency', 'response time', 'sla', 'percentile', 'p95'],
    synonyms:    ['latency test', 'sla test'],
    acronyms:    ['pt'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'perf-load-tests',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Performance',
    category:    'Pages',
    page:        'Load Tests',
    section:     null,
    description: 'k6-style multi-user ramp simulations with live VU/RPS/error-rate metrics.',
    icon:        'TrendingUp',
    badge:       null,
    navPath:     'Performance › Load Tests',
    nav:         { page: 'perf', sub: 'load-tests', tab: null, section: null, anchor: null, action: null },
    keywords:    ['load test', 'stress test', 'ramp', 'concurrent users', 'k6', 'throughput'],
    synonyms:    ['stress testing', 'load simulation'],
    acronyms:    ['lt'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'perf-groups',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Performance',
    category:    'Pages',
    page:        'Test Groups',
    section:     null,
    description: 'Bundle performance and load tests into a suite — run sequentially or in parallel.',
    icon:        'Layers',
    badge:       null,
    navPath:     'Performance › Test Groups',
    nav:         { page: 'perf', sub: 'groups', tab: null, section: null, anchor: null, action: null },
    keywords:    ['test group', 'suite', 'campaign', 'regression suite'],
    synonyms:    ['test suite', 'group runs'],
    acronyms:    [],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'perf-scheduler',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Performance',
    category:    'Pages',
    page:        'Performance Scheduler',
    section:     null,
    description: 'CRON-scheduled performance/load/group runs with queue status and concurrency capping.',
    icon:        'CalendarClock',
    badge:       null,
    navPath:     'Performance › Scheduler',
    nav:         { page: 'perf', sub: 'scheduler', tab: null, section: null, anchor: null, action: null },
    keywords:    ['scheduler', 'schedule', 'cron', 'queue', 'automated', 'recurring'],
    synonyms:    ['performance scheduler', 'schedule tests'],
    acronyms:    ['sched'],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
  {
    id:          'perf-runs',
    entityType:  ENTITY_TYPE.PAGE,
    module:      'Performance',
    category:    'Pages',
    page:        'Run History',
    section:     null,
    description: 'Full history of performance/load/group runs — filter by type, status, and date.',
    icon:        'History',
    badge:       null,
    navPath:     'Performance › Run History',
    nav:         { page: 'perf', sub: 'runs', tab: null, section: null, anchor: null, action: null },
    keywords:    ['run history', 'past runs', 'results', 'k6 runs', 'executions'],
    synonyms:    ['execution history', 'test results'],
    acronyms:    [],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },

  // ── Reports ────────────────────────────────────────────────────────────────
  {
    id:          'perf-report-runs',
    entityType:  ENTITY_TYPE.REPORT,
    module:      'Performance',
    category:    'Reports',
    page:        'Performance Run Report',
    section:     null,
    description: 'Detailed report of performance test runs — latency percentiles, error rates, throughput.',
    icon:        'History',
    badge:       null,
    navPath:     'Performance › Run History',
    nav:         { page: 'perf', sub: 'runs', tab: null, section: null, anchor: null, action: null },
    keywords:    ['performance report', 'load report', 'benchmark report', 'response time report'],
    synonyms:    ['performance results', 'load test report'],
    acronyms:    [],
    disabled:    false,
    permission:  null,
    metadata:    {},
  },
];

export const performanceProvider = {
  id:       'performance',
  type:     PROVIDER_TYPE.STATIC,
  priority: 25,
  getItems: () => ITEMS,
};
